apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: foo
  namespace: testns
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"